[versions]
java = "17"
checkstyle = "10.12.5"
spotbugs = "4.8.2"

[plugins]
spotbugs = { id = "com.github.spotbugs", version = "6.0.2" }
versions = { id = "com.github.ben-manes.versions", version = "0.50.0" }

[libraries]
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
spotbugsContrib = "com.mebigfatguy.sb-contrib:sb-contrib:7.6.3"
